### ISSUE TITLE
Update to `models.lpips.py` to support non-ancient TorchVision

### ISSUE THREAD

**Issue by tristanengst** [zvict/papr#5] opened 2024-01-30 00:57 UTC
Update line 11 of `models.lpips.py` to be
```
vgg_pretrained_features = tv.vgg16(weights=tv.VGG16_Weights.IMAGENET1K_V1 if pretrained else None).features
```
This avoids an annoying error thrown with up-to-date TorchVision versions. The last time the current version wouldn't have done with was mid 2022.

**Comment by zvict** [comment] 2024-01-30 07:22
Thanks for the feedback! The issue is fixed in [commit ](https://github.com/zvict/papr/commit/24cebcf01ce08badc308abfdfa18e68d9fb636b2)

**Closed as completed by zvict** 2024-01-30 07:22 UTC
